data_dir: "../../../../MidasData"
output_dir: "../MidasOutput"
tickers: ["MRNA", "NVDA", "CRWD"]  # Add your tickers here
combine_tickers: True  # Whether to train single unified model
resample_freq: "1H"    # 1H, 4H, 1D
n_states_range: [3, 4] # Test states 3-5
features:
  - returns
  - volatility
  - rsi
  - macd
  - atr
  - volume_change
  - obv
